import Config

# Load .env file in development (if dotenvy is available)
if Code.ensure_loaded?(Dotenvy) and File.exists?(".env") do
  Dotenvy.source!([".env"])
end

# Configure your database
config :feed_me, FeedMe.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "feed_me_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :feed_me, FeedMeWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "qyW5AsbRnefcuM9Oc1sGk+b3nJISVantMiRY+ztrCcOzRGwzBQDYFttHbvrPA8mp",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:feed_me, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:feed_me, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :feed_me, FeedMeWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Gettext translations
      ~r"priv/gettext/.*\.po$"E,
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/feed_me_web/router\.ex$"E,
      ~r"lib/feed_me_web/(controllers|live|components)/.*\.(ex|heex)$"E
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :feed_me, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# Shorter debounce for Pantry Sync in dev (30 seconds instead of 10 minutes)
config :feed_me, FeedMe.Pantry.Sync,
  debounce_ms: :timer.seconds(30),
  enabled: true

# Google OAuth credentials (loaded from .env via dotenvy above)
config :ueberauth, Ueberauth.Strategy.Google.OAuth,
  client_id: System.get_env("GOOGLE_CLIENT_ID"),
  client_secret: System.get_env("GOOGLE_CLIENT_SECRET")

# OpenRouter API configuration
config :feed_me, :openrouter,
  api_key: System.get_env("OPENROUTER_API_KEY"),
  default_model: System.get_env("OPENROUTER_DEFAULT_MODEL", "anthropic/claude-3.5-sonnet")

# Encryption key for API keys
config :feed_me, :encryption_key, System.get_env("ENCRYPTION_KEY")
